### PR TITLE
chore: use Node.js 6, 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hm, I see you did the changes yourself. Is there a reason why the PR is not preferred or merged instead? Just wondering.

**Comment by DanielRuf** [comment]
`Allow edits from maintainers.` is always enabled so you can always push commits on my branch ;-)

**Comment by tivie** [comment]
Yeah, I was getting a local conflict and was in a rush to test it locally. I usually just fixed them in local, push the changes and then merge, so people won't lose credit for changes :)

It's lazy but it's faster (appveyor takes a long time testing)

**Comment by DanielRuf** [comment]
`git stash` and friends to the rescue =)

Thanks for taking care of it 👍

**Pull request merged**
