### PR TITLE
inserted mathjax extension from https://gist.github.com/xentec/6588519

### PR DESCRIPTION
**Pull request by GlassGhost**
Signed-off-by: GlassGhost <roypfund@gmail.com>

Attempting to solve [Issue #134 - How can I use showdown with MathJax](https://github.com/showdownjs/showdown/issues/134)

### CODE REVIEW

**Comment by GlassGhost** [comment]
OK I got it working you may want to add a call to `MathJax.Hub.Queue(["Typeset",MathJax.Hub,"SOMEHTML"]);` to the html before it is sent in the `converter.makeHtml(SomeMarkdown)` and you may also want to add <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>
 with java-script somehow.

Other than that is working beautifully in my local copy of  @ https://github.com/MinJSLib/gh-template but the online version is not working as I'm having trouble using git gui and remotes, will fix soon ; )

**Comment by pdeschen** [comment]
Would you mind having your extension into its own `showdown-mathjax` repo? We're in the process of extracting all extensions into their own repository and would like the community to do so as well. Have a look at [twitter extension](https://github.com/showdownjs/twitter-extension) for inspiration.

**Comment by GlassGhost** [comment]
Uh, I don't know if I'm qualified to do that. I didn't even make the source that xentec guy did.

However I would love to be a tester.

**Comment by GlassGhost** [comment]
Actually go ahead and create that `showdown-mathjax` repo & give me full privileges there I think I can handle it.

**Comment by GlassGhost** [comment]
?

**Comment by SyntaxRules** [comment]
:+1:

**Comment by pdeschen** [comment]
@GlassGhost you may create your own repo within your user space. Then we'll add a reference to it within the wiki [section](https://github.com/showdownjs/showdown/wiki/extensions#community)

**Comment by GlassGhost** [comment]
"we'll add a reference to it within the wiki section" sounds like you're brushing me aside.

I am NOT the only one who wanted mathjax support, I did all the work for yal and you won't accept it.

Apparently this project is more concerned with how the library [works with twitter](https://github.com/showdownjs/showdown/blob/master/src/extensions/twitter.js), than actual markup.

**Comment by tivie** [comment]
@GlassGhost I'm sorry, maybe we didn't explain it properly.

Currently, we're moving all extensions previously bundled with showdown to their own repository since we feel it's better to separated extensions from the main library. This helps us to focus on developing the core library better and more swiftly while maintaining the core library compliant with the original specs and the ability to add extra features as extensions. Those extensions would then be listed in our wiki, so that users could quickly find them.

Also, we do think MathJax support is a great idea. However, as I explained before, we simply can't be responsible for developing the MathJax extension. What we suggested was that you could create a repository with the extension. Then we would add it as a "sponsored" extension in our wiki and provide you some help in developing it.

**Comment by SyntaxRules** [comment]
@tive @pdeschen Do we want to create a mathjax extension repo inside the showdown organization or have it external to the showdown org? I'm happy to create repo in the org and move this over.

**Comment by pdeschen** [comment]
@SyntaxRules On one hand, I would be tempted to leave this aside as a self-protective reaction to the way @GlassGhost rudely behave regarding support for this. On the other hand, mathjax is really a nice use case for extensions. @tivie Thoughts?

**Comment by tivie** [comment]
My only issue is maintaining the extension. (writing tests, documentation, etc...) Although I do agree mathjax support is an excellent feature, so if anyone takes charge of it, that would be awesome.

**Comment by GlassGhost** [comment]
@pdeschen I'm not questioning whether I was/wasn't rude, however I am curious what specifically I did that you felt was rude.

**Pull request closed without merging**
