### PR TITLE
Fix tables bug

### PR DESCRIPTION
**Pull request by yaniswang**
When users want show table markdown code in codeblock, it will show a table, not code.

like this:

    | Left-Aligned  | Center Aligned  | Right Aligned |
    | :------------ |:---------------:| -----:|
    | **col 3 is**      | some wordy text | $1600 |
    | ~~col 2 is~~      | centered        |   $12 |
    | zebra stripes | are neat        |    $1 |

### CODE REVIEW

**Comment by yaniswang** [comment]
Extenstion api is not strong enough, can't use subParser,globals.gHtmlBlocks...

**Comment by tivie** [comment]
@yaniswang Thanks. 

You shouldn't need to call `showdown.subParser('hashBlock')` since blocks are not really allowed inside tables.

> Extenstion api is not strong enough, can't use subParser,globals.gHtmlBlocks...

Also, in extensions, you should not call subParser directly at all since it's not meant for that.

**Comment by yaniswang** [comment]
I sugges save the table code in hash.

I add a extention latex, match by $xxx$

    | Left-Aligned  | Center Aligned  | Right Aligned |
    | :------------ |:---------------:| -----:|
    | **col 3 is**      | some wordy text | $1600 |
    | ~~col 2 is~~      | centered        |   $12 |
    | zebra stripes | are neat        |    $1 |

    Inline LaTeX: $E=mc^2$

If table not save in hash, it will render badly.

**Comment by tivie** [comment]
@yaniswang Sorry, do you mind explaining a bit further the problem you're having?

**Pull request closed without merging**
