### PR TITLE
Add ESM Support

### PR DESCRIPTION
**Pull request by evanplaice**
This PR adds preliminary ES module support with the absolute minimum changes to the existing codebase.

**Changes:**

- adds a second grunt-concat aliases to concat_esm
- removed the traditional `loaders.js` from the .esm.js config to avoid conflicts with `module.exports`
- assigns the IIFE to a variable and assigns it to the default export
- removes the `this` binding to global scope, ESM enforces `strict mode` by default so binding to global `this` is not allowed.
- generated new dist files
- added 'grunt build-esm' to trigger the build
- add `grunt build-esm` to the prerelease steps

**Usage**

This assumes the module is being used in a browser (ie hence no bare import specifier) that includes ESM support.

```javascript
import Showdown from '/node_modules/showdown/dist/showdown.esm.js';

const raw = '' // <- assume some raw markdown here
const md = new Showdown.Converter().makeHtml(raw);
document.getElementById('some-element').innerHTML = md;
```

Ref: #660

### CODE REVIEW

**Comment by evanplaice** [comment]
Note: Changed extension from `.mjs` to `.esm.js`. Even in Node `.mjs` is no longer required to use ECMAScript modules.

**Comment by Marshal27** [comment]
It's unfortunate this wasn't consumed... maybe there is a legitimate reason by the maintainers I haven't been able to find?

Regardless, I have an Open-Wc lerna repo that is a pure ES build pipeline and received a feature request to parse HTML to markdown and vice versa... there are not any ES libraries that can do bi-directional; your dist in this PR helped me out a lot and I thank you for doing this work... so far works wonderfully to solve my issue!

**Comment by mansona** [comment]
Hey @evanplaice 👋  just curious why you closed this PR? I know it was open for a little while but I wonder if we should open it again to help try to get it merged. What do you think?

**Comment by evanplaice** [comment]
This PR sat for more than a year without a response from the Maintainers

As an Author, Maintainer, and Contributor of many many projects; tracking the status of a single PR that sat untouched for >1 year isn't really a good use of my time. 

The minimal set of changes required to convert Showdown to ESM are available in this PR. Showdown's Maintainers can always pick up where I left off if they decide to make the change. I just did the work so if/when they decide to make the switch, it'll be an easy transition.

In that regard. Please do not ping me again from this project unless you are an active Maintainer.

**Pull request closed without merging**
