### PR TITLE
Fix Quick Example

### PR DESCRIPTION
**Pull request by adam-beck**

### CODE REVIEW

**Comment by tivie** [comment]
fixed in https://github.com/showdownjs/showdown/commit/b63f602fff8dcabf4403f1431265a6a06bdb20f0

**Comment by adam-beck** [comment]
Did you just steal my work?

**Comment by tivie** [comment]
> Did you just steal my work?

No, there was already a pull request similar to yours.

https://github.com/showdownjs/showdown/pull/139


2015-04-22 15:22 GMT+01:00 Adam Beck <notifications@github.com>:

**Comment by adam-beck** [comment]
Which is why I deleted my comment before you commented. Sorry for making a mistake.

**Comment by tivie** [comment]
No prob mate

**Pull request closed without merging**
