### PR TITLE
added a vimeo extension that embeds a video

### PR DESCRIPTION
**Pull request by 97-109-107**

### CODE REVIEW

**Comment by pdeschen** [comment]
Would need own repo.

**Comment by tivie** [comment]
I will look into adding these extensions to their own repo. Some of them are really worth saving.

**Comment by Sophie-OS** [comment]
maybe add it to your other extension called youtube. If you could implement this it would be a must

**Comment by tivie** [comment]
https://github.com/showdownjs/youtube-extension/commit/07d02e6db4f7ee5be6c88cffb9a0fb31d5ce9d8f

**Pull request closed without merging**
