### PR TITLE
Add youtube extension

### PR DESCRIPTION
**Pull request by mehulkar**

### CODE REVIEW

**Comment by tivie** [comment]
Extensions will live in their own repository from now on. I will crate a new repo with your contribution

**Comment by SyntaxRules** [comment]
@pdeschen Can you create a repo for this? (I am unable)

**Comment by pdeschen** [comment]
@SyntaxRules [done](https://github.com/showdownjs/youtube). 

Eventually, we should create a [yeoman generator](http://yeoman.io/authoring/) for extensions :-) There's much boilerplate that could be leveraged.

**Comment by SyntaxRules** [comment]
Closed in favor of https://github.com/showdownjs/youtube/pull/1

Thank you to everyone who did all the hard work for this (The pull is a copy and paste of your hard work). @mehulkar

**Comment by mehulkar** [comment]
Awesome, thanks! Glad this project is active :)

On Tuesday, May 26, 2015, Devyn Stott <notifications@github.com> wrote:

> Closed in favor of showdownjs/youtube#1
> <https://github.com/showdownjs/youtube/pull/1>
>
> Thank you to everyone who did all the hard work for this (The pull is a
> copy and paste of your hard work). @mehulkar <https://github.com/mehulkar>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/showdownjs/showdown/pull/73#issuecomment-105645892>.
>


-- 

------
Mehul Kar
@mehulkar

**Comment by pdeschen** [comment]
@mehulkar as a phoenix, with hard work from @tivie !

**Comment by mehulkar** [comment]
My code is problematic by the way. See the comment I left. The global
variable assign is to Twitter instead of YouTube. It should probably be
fixed in the port as well.

On Tuesday, May 26, 2015, Pascal Deschênes <notifications@github.com> wrote:

> @mehulkar <https://github.com/mehulkar> as a phoenix, with hard work from
> @tivie <https://github.com/tivie> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/showdownjs/showdown/pull/73#issuecomment-105650940>.
>


-- 

------
Mehul Kar
@mehulkar

**Comment by pdeschen** [comment]
@mehulkar thanks for pointing that out. We'll be adding test cases before publish so no worry we'll catch this. 
cc @SyntaxRules

**Pull request closed without merging**
